# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학 연산
- 배열 -> 행렬 (선형대수)
- 선형대수, 푸리에 변환 -> 수학 함수

In [ ]:
import numpy as np  # numpy 모듈을 np라는 이름으로 불러오겠다.

In [ ]:
a = np.array([1,2,3,4])  # 1차원 배열 생성   ,로 구분 x
print(a)

[1 2 3 4]


In [ ]:
l = [1,2,3,4]   # ,로 구분
print(l)

[1, 2, 3, 4]


In [ ]:
print(a.shape)  # 배열 축의 크기

(4,)


In [ ]:
print(a.ndim)   # 배열의 차원을 알고싶을 때

1


In [ ]:
print(a.dtype)  # 배열의 데이터 타입

int64


In [ ]:
print(a.itemsize)  # 각 요소의 바이트 단위 크기

8


In [ ]:
# 2차원
b = np.array([[1,2], [3,4]])
print(b)
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)  # 메모리 크기 반환

In [ ]:
# 3차원
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

In [ ]:
# 하나의 숫자값: 스칼라

s = np.array(1)
print(s)

1


In [ ]:
# 1차원: 벡터
v = np.array([1,2,3])
print(v)

[1 2 3]


In [ ]:
# 2차원: 행렬(Matrix)
m = np.array([[1,2,3],[1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [ ]:
# 3차원: 텐서(Tensor)
t = np.array([[[1,2], [1,2]], [[1,2],[1,2]]])
print(t)

In [ ]:
# for 문을 이용해서 배열 생성
f = np.array([i for i in range(0,10,2)])  # (start, end, step)
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


## 1.1 데이터 타입

1. 숫자형

2. 문자형

3. 논리형

### 숫자형
- 부호가 있는 정수(Signed integer)  int
- 부호가 없는 정수(Unsigned integer)  uint
- 실수(floating point)  float
- 복소수(complex)  complex        

In [ ]:
# int (8bit, 16bit, 32bit, 64bit)  -> 각각 처리할 수 있는 데이터의 크기

data = [1.1, 2, 3]

i = np.array(data, dtype=np.int32)   # int로 설정해서 1.1이 1로 나옴
print(i)

[1 2 3]


In [ ]:
f = np.array(data, dtype=np.float64)  # float로 설정해서 2, 3 -> 2.0, 3.0 으로 나옴(0은 생략)
print(f)

[1.1 2.  3. ]


In [ ]:
print(i.dtype)

int32


In [ ]:
data2 = [-1, 2, 3]

ui = np.array(data2, dtype=np.uint32)  # uint 8, 16, 32(0 ~ 4,294,967,295), 64
# uint32는 (0 ~ 4,294,967,295)의 범위만 나타낼 수 있어서 -1은 0에서 뒤로 간 4,294,967,295 이 나온다.

print(ui)

[4294967295          2          3]


In [ ]:
c = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex64)
print(c)
print(c.real)  # 실수
print(c.imag)  # 허수

[1.+2.j 3.+4.j 5.+6.j]
[1. 3. 5.]
[2. 4. 6.]


### 문자형
- string_
- unicod_


In [ ]:
# 데이터 타입을 왜 분류하는가 -> 용도에 따라 다르게 저장한다.
# string 은 바이트로 저장하고 보여주기 때문에? 내용물을 볼 필요가 없이 그냥 적은 용량으로 저장
# unicod 는 내용물을 볼 수 있게 저장. 용량은 더 커짐

In [ ]:
data = [1, 2, 3]

s = np.string_(data)   # bit 단위로 표현 내용물을 볼 필요는 없고 그냥 적은 용량으로 저장할 때
print(s)

b'\x01\x02\x03'


In [ ]:
print(s.dtype)  # S3: string 3  -> 3 개로 되어있다

|S3


In [ ]:
data3 = [1, 2, 3, 4, 5]

# string_
s2 = np.string_(data3)  # s2_ = np.array(data3, dtype='S) 와 같음

# print, 그 자체, 데이터 타입
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [ ]:
u = np.array(data3, dtype='U') # unicode   bit와는 다르게 내용물을 볼 수 있도록 저장(용도에 따른 저장방법)

print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [ ]:
data4 = [11, 22, 33, 44, 55]

u2 = np.array(data4, dtype='U')

print(u2)
print(u2.dtype)

['11' '22' '33' '44' '55']
<U2


### 논리형(boolean)

- True(1), False(0)
- 비트 연산 사용: & and, | or, ^ xor, ~ not

In [ ]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [ ]:
and_ = np.logical_and(l1, l2)   # and 연산으로 l1, l2 를 비교하겠다.
print(and_)

[False False False]


## 1.2 데이터 형 변환 (Cast, Casting 형 변환)

- 데이터들끼리 형태를 맞춰줌
- ex) 이미지 데이터 -> uint 형으로 불러옴 -> float로 형 변환

In [ ]:
data = [1.1, 2, 3]

a = np.float64(data)  # dtype변경 (np.데이터타입 을 이용한 방법) / a = np.array(data, dtype=np.float64) ?

print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [ ]:
a = a.astype(np.int64)   # dtype변경 (astype을 이용한 방법 - DataFrame.astype(dtype.변경할 타입)

print(a)
print(a.dtype)

[1 2 3]
int64


In [ ]:
# 변환 방법 3가지?

data = [1.1, 2, 3]

a = np.float64(data)  # dtype변경 (np.데이터타입 을 이용한 방법) / 
b = np.array(data, dtype=np.float64)
c = a.astype(np.float64)

print(a)
print(a.dtype)
print(b)
print(b.dtype)
print(c)
print(c.dtype)

In [ ]:
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [ ]:
b = b - 1   # -1 을 빼줬기 때문에 자동으로 형이 변환됨?
print(b)
print(b.dtype)

-1
int64


In [ ]:
c = np.uint16(-1)
print(c)

65535


## 1.3 산술연산

In [ ]:
# 시간비교  - 나중에
import time

data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

start_time = time.time()

for i in range(len(data)):
  for j in range(len(data[0])):

In [ ]:
data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

print(len(data))
print(len(data[0]))

2
3


In [ ]:
sum = 0

for i in range(len(data)): 
  for j in range(len(data[0])):
    #print('i:', i, 'j: ', j)
    sum += data[i][j]

print(sum)

# i가 0일 때 j는 0,1,2 

i: 0 j:  0
i: 0 j:  1
i: 0 j:  2
i: 1 j:  0
i: 1 j:  1
i: 1 j:  2
0


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

sum = a+b
min = a-b
mul = a*b
div = a/b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
a = np.array([1,2,3])
b = np.array([4,5,6])

aa = np.exp(a)  # 지수함수
print(aa)

bb = np.log(b)  # 자연로그
print(bb)

cc = np.log2(b)  # 밑이 2인 로그
print(cc)

d = np.array([0, np.pi/2, np.pi])  # 삼각함수
sin_ = np.sin(d)
cos_ = np.cos(d)
tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[ 2.71828183  7.3890561  20.08553692]
[1.38629436 1.60943791 1.79175947]


## 1.4 배열의 연결과 분할

In [ ]:
print('a'+'b')

In [ ]:
x = [1, 2, 3]
y = [4, 5, 6]  # 같은 차원끼리 가능

concat = np.concatenate([x,y])
print(concat)

[1 2 3 4 5 6]


In [ ]:
x2 = [[1,2], [3,4]]
y2 = [[4,5], [6,7]]

concat2 = np.concatenate([x2,y2], axis=1)  # 열 병합
concat3 = np.concatenate([x2,y2], axis=0)  # 행 병합
print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
arr.reshape(2,5)   # 모양 다시 정하기

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
x2 = [[1,2], [3,4]]  # 2x2
y2 = [[4,5], [6,7]]  # 2x2

# hstack horizontal - 수평
h = np.hstack([x2, y2])
print(h)

# vstack vertical - 수직
v = np.vstack([x2, y2])
print(v)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [ ]:
x2 = np.array([[1,2], [3,4], [5, 6]])  # 2x2

# hsplit  행 분할
h2 = np.hsplit(x2, 2)
print(h2)  
# -> array([[1],[3],[5]]) / array([[2],[4],[6]])


# vsplit  열 분할
v2 = np.vsplit(x2,3)
print(v2)
# -> [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [ ]:
x5 = np.array([[1],[2],[3],[4],[5]])
print(x5)
print(x5.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [ ]:
x6 = np.array([[1, 2, 3, 4, 5]])
print(x6)
print(x6.shape)

[[1 2 3 4 5]]
(1, 5)


## 1.5 다양한 배열 만들기

In [ ]:
zero = np.zeros([3,4])
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
one = np.ones([3,4])
print(one)

In [ ]:
eye = np.eye(3)
print(eye)

# Numpy 제공 함수

In [ ]:
# 절댓값
arr1 = np.array([-1, -2, -3, 4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [ ]:
# 제곱근
arr2 = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [ ]:
# 평균
a = np.array([1, 2, 3, 4, 5])
a_mean = np.mean(a)

print(a_mean)  # float형으로 출력

3.0


In [ ]:
# 중간값
b = np.array([1, 3, 5, 7, 9])
b_median = np.median(b)

print(b_median)  # float형으로 출력

5.0


In [ ]:
# 표준편차
c = np.array([1, 2, 3, 4, 5])
c_std = np.std(c)

print(c_std)

1.4142135623730951


In [ ]:
# 분산
d = np.array([1, 2, 3, 4, 5])
d_var = np.var(d)

print(d_var)  # float형으로 출력

2.0


In [ ]:
# 합
d = np.array([1, 2, 3, 4, 5])
d_sum = np.sum(d)

print(d_sum)

In [ ]:
# 누적합계 (배열 형태로 반환)
d_cumsum = np.cumsum(d)

print(d_cumsum)

[ 1  3  6 10 15]


In [ ]:
# 최소값
min = np.argmin(d)

print(min) # 인덱스 값으로 출력. 0번째가 제일 작다

0


In [ ]:
# 최대값
max = np.argmax(d)

print(max) # 인덱스 값으로 출력. 0번째가 제일 작다

4


In [ ]:
# any -> 배열 안에 하나라도 True가 있는지 확인
a = np.array([0, 0, 0, 1])
a_true = np.any(a)

print(a_true)

True


In [ ]:
# all -> 모두 True가 아니라면 False
a_all = np.all(a)
print(a_all)

False


In [ ]:
# Nan/ nansum -> nan값이 있을 때 0으로 취급하여 더하기
a = np.array([1, 2, np.nan, 4])
a_nsum = np.nansum(a)
a_sum = np.sum(a)

print(a_sum)
print(a_nsum)

nan
7.0


In [ ]:
# where -> 조건에 맞는 값을 출력
d = np.array([1, 2, 3, 4, 5])
condition1 = np.where(d < 3)
condition = np.where(d < 3, d, 0)

print(condition1) # 튜플형태로 출력 / 값이 없어도 출력?
print(condition)  # 배열형태로 출력

(array([0, 1]),)
[1 2 0 0 0]


### Boolean Indexing

조건에 따른 요소들을 판별해서 새로운 배열을 만든다.

In [ ]:
# 조건에 맞는 값을 출력?
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_a = a[a % 2 == 0]

print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Broadcast (브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해줌
- ex) 1차원, 2차원

In [ ]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [ ]:
d = np.array([[1],[2],[3]])  # 3 x 1
e = np.array([4, 5, 6])   # 원래라면 ([[4, 5, 6]])으로 해야함 1 x 3
f = d + e

print(d.shape)
print(e.shape)
print(f)

(3, 1)
(3,)
[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원 수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때가지 1을 추가한다.

- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제한다.

- 두 배열의 차원 수가 같은 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다.

In [ ]:
z = np.array([[1,2,3]])
print(z.shape)

(1, 3)


# 브로드 캐스팅

- 두 배열의 차원의 크기가 같다. -> 그냥 계산
- 두 배열의 차원이 다르고 한 배열의 차원이 1차원(벡터)
- 차원을 늘렸을 때 계산이 가능한 경우

### 난수 생성 함수

**random**

In [ ]:
import numpy as np

In [ ]:
a = np.random.rand(2,2)  # rand -> 0 ~ 1 사이에 값 랜덤으로 (2,2) -> 2x2 행렬
print(a)

[[0.91688979 0.65645466]
 [0.7027827  0.98021002]]


In [ ]:
b = np.random.randn(2,2)  # 평균이 0, 분산이 1인 표준 정규 분포 생성
print(b)

[[ 0.22640086 -1.4290325 ]
 [-0.6676767   0.64522448]]


In [ ]:
c = np.random.randint(0,10,size=5)  # (최소값, 최대값, size = 몇개 만들건지)
print(c)

[5 3 9 5 0]


In [ ]:
c2 = np.random.randint(0,10,size=(2,2))  # size=(2,2) 행렬로도 만들 수 있음
print(c2)

[[0 4]
 [4 8]]


In [ ]:
d = np.arange(5)  # 0 ~ 5 까지 값을 생성
d_shuffle = np.random.shuffle(d)  # d를 무작위로 섞음, 복사본 생성x 원본이 바뀜
print(d)

[0 4 3 1 2]


In [ ]:
# choice = np.random.choice(d,5)  # d에서 5개를 뽑음 / 중복 허용
# choice = np.random.choice(d,5, replace=False)  # d에서 5개를 뽑음 / 중복 허용x

choice = np.random.choice(d, 5, p=[0.1, 0.3, 0.2, 0.3, 0.1])  # p는 전체 확률이 1이 되어야함
# d = [0,1,2,3,4]를 확률을 p=[0.1, 0.3, 0.2, 0.3, 0.1])에 맞게 뽑는 것

print(choice)

[3 1 4 4 1]


In [ ]:
# prermutation 순열
a = np.arange(10)
a_p = np.random.permutation(a)
print(a_p)
print(a)

[2 1 9 7 8 3 0 6 5 4]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# 정규분포를 따르는 난수 생성
# a = np.random.normal('평균','표준편차','갯수')
a = np.random.normal(0, 1, 3)
print(a)

[-1.04734279  1.07236809 -0.41573271]


In [ ]:
data = [1.1, 2, 3]

a = np.float64(data)  # dtype변경 (np.데이터타입 을 이용한 방법) / 
b = np.array(data, dtype=np.float64)
c = a.astype(np.float64)

print(a)
print(a.dtype)
print(b)
print(b.dtype)
print(c)
print(c.dtype)

[1.1 2.  3. ]
float64
[1.1 2.  3. ]
float64
[1.1 2.  3. ]
float64


# 연습문제(Numpy)

In [ ]:
import numpy as np

In [ ]:
# 4.1 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

# concat 함수
a = np.concatenate([arr1,arr2,arr3])
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [ ]:
# 4.2 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.
# mean() 함수 응용하기

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
c = []

for i in range(len(arr[0])):
  b = np.mean(arr[i])
  c.append(b)
  d = np.array(c)

print(d)
print(d.ndim)  # 차원 확인

[2. 5. 8.]
1


In [ ]:
# 4.3 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.
# np.max()

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_max1 = arr.max(1)
print(arr_max1)

# np.max(arr, axis=1)

array([3, 6, 9])

In [ ]:
# 4.4 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.
# np.linspace(시작범위, 끝범위, num개수)

x = np.linspace(0,1,10)
print(x) 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
# 4.5 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.
# def sum_of_evens(arr: np.ndarray) -> int:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even = arr[arr % 2 == 0]
es = np.sum(even)
print(es)

# def sum_of_evens(arr: np.ndarray) -> int:
#     evens = arr[arr % 2 == 0]  # 짝수인 요소 선택
#     return np.sum(evens)  # 짝수인 요소들의 합 반환

30


In [ ]:
# 4.6 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

# 1. 수평분할하기 
harrd = np.hsplit(arr,2)
print(harrd)

# 다시 원본으로 스택쌓기
harrs = np.hstack(harrd)
print(harrs)

# arr_1 = arr_split[0]
# arr_2 = arr_split[1]
# arr_stack = np.hstack((arr_1, arr_2))
# print(arr_stack)

# 2. 수직분할하기 
varrd = np.vsplit(arr,3)
print(varrd)

# 다시 원본으로 스택쌓기
varrs = np.vstack(varrd)
print(varrs)

# arr_1 = arr_split[0]
# arr_2 = arr_split[1]
# arr_3 = arr_split[2]
# arr_stack = np.vstack((arr_1, arr_2, arr_3))
# print(arr_stack)

In [ ]:
# 4.7 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))

# a = arr[arr % 10 == 0]
# print(a)

a10 = np.where(arr % 10 == 0, arr, 0)
print(a10)

[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


In [ ]:
# 4.8 [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

n = a[a % 2 == 0]
print(n)

[2 4 6 8]


In [ ]:

bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
# 1-----------------------------------
# n = a[bool_indexing_array];
# print(n)    

# 2-----------------------------------
# bool_indexing = (a % 2 == 0)
# print(bool_indexing)
# print(a[bool_indexing])

# 3-----------------------------------
# n = a[ a % 2 == 0 ]
# n

array([2, 4, 6, 8])

In [ ]:
# 4.9 각도를 이용해서 삼각함수를 만들어봅시다.
angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

# 사인 함수 계산
sin_value = np.sin(angle)
print("사인 값:", sin_value)

# 코사인 함수 계산
cos_value = np.cos(angle)
print("코사인 값:", cos_value)

# 탄젠트 함수 계산
tan_value = np.tan(angle)
print("탄젠트 값:", tan_value)

62.831853071795855

In [ ]:
# 4.10 조건함수를 사용해서  짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.
arr = np.array([1, 2, 3, 4, 5])

arre2 = np.where(arr % 2 == 0, arr, 0)
anr = arre2 *2

print(anr)

# new_arr = np.where(arr % 2 == 0, arr * 2, arr)
# print("조건을 만족하는 요소를 2배로:", new_arr)

[0 4 0 8 0]


# Pandas

- 데이터 자체를 분석, 파악
- 표
- 데이터 다루는 데 초점
- 정렬, 필터링, 그룹화, 집계

- 데이터 로딩 및 저장
- 데이터 인덱싱 및 슬라이싱
- 결측치 처리
- 데이터 변환
- 데이터 집계 및 그룹화
---
- 시계열 데이터 처리
- 데이터 시각화

## 1. Series(시리즈)

- 인덱스를 지정할 수 있음

In [2]:
import pandas as pd

In [ ]:
# Series를 만드는 방법 3가지 (리스트, 딕셔너리, 스칼라)

In [ ]:
s = pd.Series([1,2,3,4])  # 리스트로 만들기 / Series -> 첫번째 열에 인덱스를 지정해줌 (번호맥여줌?)
print(s)

0    1
1    2
2    3
3    4
dtype: int64


In [ ]:
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})  # 딕셔너리로 만들기
print(s2)

a    1
b    2
c    3
d    4
dtype: int64


In [ ]:
s3 = pd.Series(5, index=[0,1,2])  # 스칼라(그냥 숫자값)로 만들기
print(s3)

0    5
1    5
2    5
dtype: int64


In [ ]:
s3 = pd.Series(5, index=range(1,10))  # index를 이런식으로 정해줄 수 있다.
print(s3)

In [ ]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series)


a    1
b    2
c    3
d    4
e    5
dtype: int64


In [ ]:
# 자동으로 인덱싱 된 것을 다시 바꾸기?
s = pd.Series(data)
print(s)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [ ]:
data = [1, 2, 3, 4, 5]
index = ['a', 'b', 'c', 'd', 'e']
series = pd.Series(data, index=index)
print(series)

a    1
b    2
c    3
d    4
e    5
dtype: int64


## 슬라이싱
- 원본을 바꾸지 않음

In [3]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)
print(series)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [17]:
series[:-1]

0    1
1    2
2    3
3    4
dtype: int64

### Boolean indexing

In [22]:
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

print(series[series > 2])  # a[a조건]

2    3
3    4
4    5
dtype: int64


In [23]:
# 5보다 작은 시리즈 만들기
data = [1, 2, 3, 4, 5]
series = pd.Series(data)

print(series[series < 5])

0    1
1    2
2    3
3    4
dtype: int64


### Series 산술연산

In [ ]:
print(series +100)
print(series -100)
print(series *100)
print(series **100)
print(series /100)   # 몫 float형 소수점o
print(series //100)  # 몫 int형 소수점x
print(series %100)
# 곱하기 * / 제곱 ** / 나누기 /, // / 나머지 %

## Series 객체에 접근
- keys  -> index
- values

index를 부를 때 keys는 index를 가르키기 때문에 keys와
index를 통해 불러올 수 있다.?

In [ ]:
print(series.keys)
'''
<bound method Series.keys of 
0    1
1    2
2    3
3    4
4    5
dtype: int64>
'''
print(series.values)

In [31]:
print(series.keys())
print(series.index)
print(series.values)

RangeIndex(start=0, stop=5, step=1)
RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [27]:
s2 = pd.Series({'a': 1, 'b': 2, 'c': 3, 'd': 4})  # 딕셔너리로 만들기
print(s2.keys())

<bound method Series.keys of a    1
b    2
c    3
d    4
dtype: int64>


In [29]:
s2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [32]:
# items
print(s2.items())

# zip - 순회가능하고 쌍으로 이루어진 경우

In [35]:
for index, value in s2.items():
  print(f'인덱스: {index}, 데이터: {value}')

인덱스: a, 데이터: 1
인덱스: b, 데이터: 2
인덱스: c, 데이터: 3
인덱스: d, 데이터: 4


In [38]:
s = pd.Series([10, 20, 30, 40], index = ['a', 'b', 'c', 'd'])
print(s)

a    10
b    20
c    30
d    40
dtype: int64


In [42]:
# loc -> 행에 접근 / 레이블로 불러오기 때문에 레이블을 입력해야함(b 인덱스 -> 'b')
print(s.loc['b'])  # 'b' 하나만 지정해줬기 때문에 b행의 값만 알려줌
print(s.loc['b':'d']) # 'b':'d' 로 지정해줘서 특정할 수 없기 때문에 다 알려줌?

20
b    20
c    30
d    40
dtype: int64


In [43]:
# iloc -> (행에 기반한) 열에 접근  value 값을 출력?
print(s.iloc[1])  
print(s.iloc[1:3])
# a    10
# b    20 
# c    30
# d    40

20


In [46]:
# at -> index값을 지정하여 불러올 때? loc와 비슷하지만 하나의 값만 가져올 때
print(s.at['a'])

10


In [47]:
# iat 에 기반
print(s.iat[0])

20


In [51]:
# get 없는 값에 대한 처리 방법 
# at에 없는 값을 넣으면 error가 나지만 get은 error가 아니라 없다는 것을 알려줌
print(s.get('e', default = -1))  # default = 없는값을 표현할 숫자

-1


## 결측값 (NaN, None)
- isna()
- isnull()

- NaN(Not a number) -> 데이터타입: float 
- None -> 데이터타입: none

In [ ]:
import numpy as np
import pandas as pd

In [53]:
data = [1, 2, 3, None]
print(np.array(data))  # np -> None을 None으로 인식

[1 2 3 None]


In [54]:
print(pd.Series(data))  # pd -> None을 NaN으로 인식 / NaN은 float형이라 error를 줄일 수 있다?

0    1.0
1    2.0
2    3.0
3    NaN
dtype: float64


In [69]:
s = pd.Series(data)  # isna(), isnull()
print(s.isna())
print(s.isnull().sum())  # .sum() -> True값을 더해줌 (빈값의 개수를 알 수 있음)

0    False
1    False
2    False
3     True
dtype: bool
1
[1. 0. 0. 0.]


In [70]:
print(s.notnull().sum()) # null값이 아닌 값의 수

3


결측치를 제거

In [72]:
s.dropna()  # NaN값을 날려줌?

0    1.0
1    2.0
2    3.0
dtype: float64

결측치를 0으로 치환

In [73]:
s.fillna(0)  # 빈값을 0으로 채워줌

0    1.0
1    2.0
2    3.0
3    0.0
dtype: float64

## Series 함수

In [74]:
s = pd.Series([1, 3, 5, 7, 9])

In [75]:
s.count()  # 원소의 수

5

In [ ]:
s.min()  # 최소값
s.max()  # 최대값

In [76]:
print(s.mean())
print(s.median())
print(s.std())
print(s.var())

5.0
5.0
3.1622776601683795
10.0


In [77]:
s.describe()  # 기초통계 내용

count    5.000000
mean     5.000000
std      3.162278
min      1.000000
25%      3.000000
50%      5.000000
75%      7.000000
max      9.000000
dtype: float64

# 연습문제(Numpy, Pandas)

## 배열

In [ ]:
import numpy as np

In [108]:
# 1. 사이즈 10의 Null(0) 1차원 배열을 만들어 보세요.
# array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

a = np.array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])
print(a)

# a = np.zeros(10)
# print(a)

[0 0 0 0 0 0 0 0 0 0]


In [110]:
# 2. 값이 10 ~ 49 인 1차원 배열을 만들어주세요.

b = np.array([range(10,50)])
print(b)

# b = np.arange(10,50)
# print(b)

[[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
  34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]]


In [111]:
# 3. 0~8 까지의 값을 사용하여 3x3 배열을 만드시오

c = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(c)

# c = np.aragne(9).reshape(3,3)
# print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [150]:
# 3.1 (응용) 5x5 배열을 만들어서 경계값만 1이고, 내부에 있는 값은 0 인 2차원 배열을 만들어 보세요

a = np.ones((5,5))
a[1:4, 1:4] = 0   # a[1:-1, 1:-1]도 똑같음
a

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

## 랜덤

In [114]:
# 4. 랜덤 값이 있는 3x3x3 array 만들기

d = np.random.rand(3,3,3)  # rand -> 0 ~ 1 사이에 값 랜덤으로 (2,2) -> 2x2 행렬
print(d)

[[[0.90001763 0.02438267 0.72082244]
  [0.7557748  0.56870761 0.38909019]
  [0.97322714 0.27317825 0.38603036]]

 [[0.85398424 0.62555929 0.34064582]
  [0.65929909 0.2386483  0.3877239 ]
  [0.39103792 0.24678124 0.33020122]]

 [[0.45590008 0.03227649 0.40644525]
  [0.86993294 0.02611757 0.56312563]
  [0.45981775 0.99740315 0.37237757]]]


In [116]:
# 5. 랜덤 값이 있는 10x10 배열을 만들고 최소값과 최대값을 찾아주세요

e = np.random.rand(10,10)
print(e.min())
print(e.max())

# e_min, e_max = e.min(), e.max()
# print(e_min, e_max)  도 가능

0.00029493457838725146
0.998504554979336


In [119]:
# 6. 30 크기의 랜덤 값을 가지는 1차원 배열을 만들어서 평균값을 도출해주세요

f = np.random.rand(30)
print(f)
print(f.mean())

[0.28329844 0.02499058 0.53144486 0.9237096  0.75737625 0.83615449
 0.72224209 0.43659455 0.17537431 0.27864148 0.58988766 0.00144369
 0.84237822 0.64407659 0.22412157 0.96387127 0.81792402 0.35477284
 0.58988198 0.91114951 0.13132916 0.48363252 0.03709949 0.0158652
 0.54756808 0.53025638 0.15269432 0.96069173 0.28656035]
0.4846562484046764


## 행렬

In [166]:
# 7. 1로 채워진 5x3 행렬과 3x2 행렬의 곱을 구해봅시다.

a = np.ones([5,3])
b = np.ones([3,2])

print(a@b)  # 왜 *이 아니라 @지
# print(np.dot(a,b))  # np.dot(행렬1, 행렬2)  / 행렬끼리 곱할 때

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


In [152]:
# 7.1 (응용) 행렬의 연산을 하고 제로행렬 C 에 에 값을 덮어씌워주세요.
# np.add() 함수의 매개변수를 응용합니다. 

A = np.array([1, 2, 3])
B = np.array([4, 5, 6])
C = np.zeros(3)

np.add(A, B, out=C)

print(C)

[5. 7. 9.]


In [153]:
# 7.2 (응용) A 배열의 모든 요소의 부호를 반전시켜서 C에 값을 덮어씌워주세요.
# np.negative()

np.negative(A, out=C)
C

array([-1., -2., -3.])

In [155]:
# 8. 크기 10개의 1차원 랜덤 행렬을 만들고 최대값을 0 으로 바꾸어 주세요
#    1. 최대값이 어디에 있는 지 인덱스를 확인하면
#    2. 인덱싱을 통해서 최대값을 0으로 바꿔줄 수 있습니다.
#    3. argmax() 함수는 배열의 요소들 중에서 가장 큰 값이 있는 위치의 인덱스를 반환합니다.

Z = np.random.random(10)
print('최대값이 있는 인덱스:',Z.argmax())
# Z[Z.argmax()] = 0
Z

최대값이 있는 인덱스: 5


array([0.93144294, 0.61949101, 0.31381555, 0.16040104, 0.6644659 ,
       0.94207404, 0.72723301, 0.82373896, 0.91284687, 0.6822069 ])

In [158]:
# 9. np.max 와 np.argmax 의 값을 확인해봅시다.
# 각 열과 행별로 최댓값을 반환하고 인덱스를 호출해주세요

arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr에서 최댓값:', np.max(arr))
print(f'arr에서 최댓값인 {np.max(arr)}이 위치한 인덱스:',np.argmax(arr))
print('arr에서 각 열(axis=0)별로 최댓값을 반환:', np.max(arr, axis=0))
print('arr에서 각 열(axis=1)별로 최댓값을 반환:', np.max(arr, axis=1))
print('arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=0))
print('arr에서 각 행(axis=1)별로 최댓값의 인덱스를 반환:',np.argmax(arr, axis=1))

arr에서 최댓값: 6
arr에서 최댓값인 6이 위치한 인덱스: 5
arr에서 각 열(axis=0)별로 최댓값을 반환: [4 5 6]
arr에서 각 열(axis=1)별로 최댓값을 반환: [3 6]
arr에서 각 행(axis=0)별로 최댓값의 인덱스를 반환: [1 1 1]
arr에서 각 행(axis=1)별로 최댓값의 인덱스를 반환: [2 2]


## 형변환

In [ ]:
# 10. 균일분포의 랜덤함수를 이용해서 0 ~ 100 까지 값을 가지는 1차원 실수 (32비트) 행렬을 만듭니다.
#     정수 (32비트) 이면서 배열의 모양을 10x1 로 변환해주세요

Z = (np.random.rand(10)*100).astype(np.float32)
print(Z)

X = Z.view(np.int32)
X.shape = (10,1)
X

In [ ]:
# view() 함수와 astype() 함수는 NumPy 배열에서 각각 다른 목적을 가지고 사용되는 함수입니다.
# 둘의 함수를 사용해서 차이를 이해해보세요 

Z = np.random.randint(0,6,(3,10))
print(Z)
Z.any() # == np.any(Z)

In [ ]:
# 11. 집계 함수로 배열에 Null 값이 있는지 확인해보세요.
#     정수형 난수로 3x10 행렬을 생성합니다.
#     0 ~ 5 까지의 값으로 만들어주세요.

## 정규분포, 균일분포

In [ ]:
# 12. 정규분포 normal()을 따르는 난수 생성의 방법을 배웠습니다. 
#     이번에는 주어진 범위에서 균일분포를 따르는 난수 생성을 해보겠습니다. 
#     Normal Distribution
#     Uniform Distribution
#     [low, high] 범위에서 균일 분포를 따르는 난수 생성
# random_number = np.random.uniform(low, high, size)

Z = np.random.uniform(0,1,10)
print(Z)
num = 0.5
np.abs(Z-num).argmin()

In [ ]:
# 12.1 (응용) 0부터 1사이의 10개의 값을 가지는 균일분포 배열을 만들어주세요
# 배열에서 지정된 값에서 가장 가까운 값을 찾겠습니다. => 정답 인덱스 호출 => 가장 가까운 값 호출
# num = 0.5

Z[np.abs(Z-num).argmin()]

flat() 함수는 다차원 배열을 1차원으로 평면화하는 간편한 방법을 제공합니다. 이를 통해 다차원 배열의 요소에 순차적으로 접근하거나, 1차원 배열로 변환하여 다양한 연산에 활용할 수 있습니다

In [ ]:
# 12.2 (응용) 다차원의 배열을 1차원으로 평면화 하는 flatten 함수로 응용해보겠습니다.
# np.flatten()
# 3차원의 배열을 -> 1차원으로 평면화 하고 -> 최대값을 10으로 변경해주세요

arr = np.array([[1, 2, 3], [4, 5, 6], [3, 4, 5]])

# 다차원 배열을 1차원으로 평면화
flattened_arr = arr.flat
print(arr.argmax())

# 최대값을 갖는 인덱스의 값을 10으로 변경
flattened_arr[arr.argmax()] = 10

# 평면화된 1차원 배열의 요소에 접근 가능하므로, 최대값을 갖는 인덱스에 접근하여 값 변경도 가능

print(arr) # 원본 다차원 배열 arr에도 해당 변경이 반영되는 것을 확인할 수 있습니다.


In [ ]:
# 12.3 (응용) 4차원(3,4,3,4)으로 주어진 범위(0,10) 안에서 정수형 변수를 생성해주세요
# 마지막 2축(axis)에서 합계를 출력해보세요

A = np.random.randint(0,10, (3,4,3,4))
A.sum(axis = (-2,-1))


In [ ]:
# 12.4 배열의 첫번째 행과 두번째행을 바꾸어 봅시다

A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
A

## arg 인덱스 접근 함수 추가

**배열의 인덱스에 접근하기 위해 사용할 수 있는 함수**

> np.argmax(): 배열에서 최댓값의 인덱스를 반환합니다.

> np.argmin(): 배열에서 최솟값의 인덱스를 반환합니다.

> np.argwhere(): 조건을 충족하는 요소의 인덱스를 반환합니다. 반환되는 값은 2차원 배열이며, 각 행은 해당 요소의 인덱스를 나타냅니다.

> np.where(): 조건에 따라 요소를 선택하고, 선택된 요소의 인덱스를 반환합니다.

> np.nonzero(): 0이 아닌 요소의 인덱스를 반환합니다. 반환되는 값은 각 차원별로 분리된 인덱스 배열입니다.

In [ ]:
# argmax. argmin 을 응용하기
# (응용) 표준정규분포를 사용해서 100개의 난수를 생성해주세요.
# 그 후 shuffle() 함수를 사용해서 순서를 섞어줍니다.
# sort() 함수와 마찬가지로 argsort() 를 이용해 인덱스를 사용합니다
# argsort() 를 사용해서 가장 큰 값을 5개만 뽑아봅시다.

In [ ]:
Z = np.random.randn(100)
np.random.shuffle(Z)

Z[np.argsort(Z)[-5:]]

In [ ]:
arr = np.array([1, 3, 2, 5, 4])

# 최댓값의 인덱스
max_index = np.argmax(arr)
print("Max index:", max_index)  

# 최솟값의 인덱스
min_index = np.argmin(arr)
print("Min index:", min_index)  

# 조건을 충족하는 요소의 인덱스
index = np.argwhere(arr > 2)
print("Indices greater than 2:", index)  # 반환값 2차원 [[1] [3] [4]]

# 조건에 따라 요소 선택 및 인덱스 반환
selected_index = np.where(arr > 2)
print("Selected indices:", selected_index)  

# 0이 아닌 요소의 인덱스
nonzero_index = np.nonzero(arr)
print("Nonzero indices:", nonzero_index)  
