# 1. Numpy

- 파이썬 라이브러리 중 하나 -> 과학 연산
- 배열 -> 행렬 (선형대수)
- 선형대수, 푸리에 변환 -> 수학 함수

In [1]:
import numpy as np  # numpy 모듈을 np라는 이름으로 불러오겠다.

In [3]:
a = np.array([1,2,3,4])  # 1차원 배열 생성   ,로 구분 x
print(a)

[1 2 3 4]


In [4]:
l = [1,2,3,4]   # ,로 구분
print(l)

[1, 2, 3, 4]


In [14]:
print(a.shape)  # 배열 축의 크기

(4,)


In [6]:
print(a.ndim)   # 배열의 차원을 알고싶을 때

1


In [15]:
print(a.dtype)  # 배열의 데이터 타입

int64


In [7]:
print(a.itemsize)  # 각 요소의 바이트 단위 크기

8


In [ ]:
# 2차원
b = np.array([[1,2], [3,4]])
print(b)
print(b.ndim)
print(b.dtype)
print(b.itemsize)
print(b.nbytes)  # 메모리 크기 반환

In [ ]:
# 3차원
c = np.array([[[1,2], [3,4]], [[5,6],[7,8]]])
print(c)
print(c.ndim)
print(c.dtype)
print(c.itemsize)
print(c.nbytes)

In [16]:
# 하나의 숫자값: 스칼라

s = np.array(1)
print(s)

1


In [17]:
# 1차원: 벡터
v = np.array([1,2,3])
print(v)

[1 2 3]


In [18]:
# 2차원: 행렬(Matrix)
m = np.array([[1,2,3],[1,2,3]])
print(m)

[[1 2 3]
 [1 2 3]]


In [ ]:
# 3차원: 텐서(Tensor)
t = np.array([[[1,2], [1,2]], [[1,2],[1,2]]])
print(t)

In [25]:
# for 문을 이용해서 배열 생성
f = np.array([i for i in range(0,10,2)])  # (start, end, step)
print(f)
print(f.ndim)
print(f.dtype)
print(f.itemsize)
print(f.nbytes)

[0 2 4 6 8]
1
int64
8
40


## 1.1 데이터 타입

1. 숫자형

2. 문자형

3. 논리형

### 숫자형
- 부호가 있는 정수(Signed integer)  int
- 부호가 없는 정수(Unsigned integer)  uint
- 실수(floating point)  float
- 복소수(complex)  complex        

In [26]:
# int (8bit, 16bit, 32bit, 64bit)  -> 각각 처리할 수 있는 데이터의 크기

data = [1.1, 2, 3]

i = np.array(data, dtype=np.int32)   # int로 설정해서 1.1이 1로 나옴
print(i)

[1 2 3]


In [32]:
f = np.array(data, dtype=np.float64)  # float로 설정해서 2, 3 -> 2.0, 3.0 으로 나옴(0은 생략)
print(f)

[1.1 2.  3. ]


In [27]:
print(i.dtype)

int32


In [31]:
data2 = [-1, 2, 3]

ui = np.array(data2, dtype=np.uint32)  # uint 8, 16, 32(0 ~ 4,294,967,295), 64
# uint32는 (0 ~ 4,294,967,295)의 범위만 나타낼 수 있어서 -1은 0에서 뒤로 간 4,294,967,295 이 나온다.

print(ui)

[4294967295          2          3]


In [37]:
c = np.array([1 + 2j, 3 + 4j, 5 + 6j], dtype=np.complex64)
print(c)
print(c.real)  # 실수
print(c.imag)  # 허수

[1.+2.j 3.+4.j 5.+6.j]
[1. 3. 5.]
[2. 4. 6.]


### 문자형
- string_
- unicod_


In [ ]:
# 데이터 타입을 왜 분류하는가 -> 용도에 따라 다르게 저장한다.
# string 은 바이트로 저장하고 보여주기 때문에? 내용물을 볼 필요가 없이 그냥 적은 용량으로 저장
# unicod 는 내용물을 볼 수 있게 저장. 용량은 더 커짐

In [40]:
data = [1, 2, 3]

s = np.string_(data)   # bit 단위로 표현 내용물을 볼 필요는 없고 그냥 적은 용량으로 저장할 때
print(s)

b'\x01\x02\x03'


In [41]:
print(s.dtype)  # S3: string 3  -> 3 개로 되어있다

|S3


In [42]:
data3 = [1, 2, 3, 4, 5]

# string_
s2 = np.string_(data3)  # s2_ = np.array(data3, dtype='S) 와 같음

# print, 그 자체, 데이터 타입
print(s2)
print(s2.dtype)

b'\x01\x02\x03\x04\x05'
|S5


In [43]:
u = np.array(data3, dtype='U') # unicode   bit와는 다르게 내용물을 볼 수 있도록 저장(용도에 따른 저장방법)

print(u)
print(u.dtype)

['1' '2' '3' '4' '5']
<U1


In [47]:
data4 = [11, 22, 33, 44, 55]

u2 = np.array(data4, dtype='U')

print(u2)
print(u2.dtype)

['11' '22' '33' '44' '55']
<U2


### 논리형(boolean)

- True(1), False(0)
- 비트 연산 사용: & and, | or, ^ xor, ~ not

In [45]:
l1 = np.array([True, False, True])
l2 = np.array([False, True, False])

print(l1.dtype)
print(l2.dtype)

bool
bool


In [46]:
and_ = np.logical_and(l1, l2)   # and 연산으로 l1, l2 를 비교하겠다.
print(and_)

[False False False]


## 1.2 데이터 형 변환 (Cast, Casting 형 변환)

- 데이터들끼리 형태를 맞춰줌
- ex) 이미지 데이터 -> uint 형으로 불러옴 -> float로 형 변환

In [78]:
data = [1.1, 2, 3]

a = np.float64(data)  # dtype변경 (np.데이터타입 을 이용한 방법) / a = np.array(data, dtype=np.float64) ?

print(a)
print(a.dtype)

[1.1 2.  3. ]
float64


In [50]:
a = a.astype(np.int64)   # dtype변경 (astype을 이용한 방법 - DataFrame.astype(dtype.변경할 타입)

print(a)
print(a.dtype)

[1 2 3]
int64


In [51]:
b = np.uint16(0)

print(b)
print(b.dtype)

0
uint16


In [52]:
b = b - 1   # -1 을 빼줬기 때문에 자동으로 형이 변환됨?
print(b)
print(b.dtype)

-1
int64


In [56]:
c = np.uint16(-1)
print(c)

65535


## 1.3 산술연산

In [ ]:
# 시간비교  - 나중에
import time

data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

start_time = time.time()

for i in range(len(data)):
  for j in range(len(data[0])):

In [60]:
data = [[1, 2, 3], [4, 5, 6]]
data2 = [[1, 1, 1], [2, 2, 2]]

print(len(data))
print(len(data[0]))

2
3


In [74]:
sum = 0

for i in range(len(data)): 
  for j in range(len(data[0])):
    #print('i:', i, 'j: ', j)
    sum += data[i][j]

print(sum)

# i가 0일 때 j는 0,1,2 

i: 0 j:  0
i: 0 j:  1
i: 0 j:  2
i: 1 j:  0
i: 1 j:  1
i: 1 j:  2
0


In [72]:
a = np.array([1,2,3])
b = np.array([4,5,6])

sum = a+b
min = a-b
mul = a*b
div = a/b

print(sum)
print(min)
print(mul)
print(div)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [76]:
a = np.array([1,2,3])
b = np.array([4,5,6])

aa = np.exp(a)  # 지수함수
print(aa)

bb = np.log(b)  # 자연로그
print(bb)

cc = np.log2(b)  # 밑이 2인 로그
print(cc)

d = np.array([0, np.pi/2, np.pi])  # 삼각함수
sin_ = np.sin(d)
cos_ = np.cos(d)
tan_ = np.tan(d)

print(sin_)
print(cos_)
print(tan_)

[ 2.71828183  7.3890561  20.08553692]
[1.38629436 1.60943791 1.79175947]


## 1.4 배열의 연결과 분할

In [ ]:
print('a'+'b')

In [79]:
x = [1, 2, 3]
y = [4, 5, 6]  # 같은 차원끼리 가능

concat = np.concatenate([x,y])
print(concat)

[1 2 3 4 5 6]


In [84]:
x2 = [[1,2], [3,4]]
y2 = [[4,5], [6,7]]

concat2 = np.concatenate([x2,y2], axis=1)  # 열 병합
concat3 = np.concatenate([x2,y2], axis=0)  # 행 병합
print(concat2)
print(concat3)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [86]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [97]:
arr.reshape(2,5)   # 모양 다시 정하기

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [98]:
x2 = [[1,2], [3,4]]  # 2x2
y2 = [[4,5], [6,7]]  # 2x2

# hstack horizontal - 수평
h = np.hstack([x2, y2])
print(h)

# vstack vertical - 수직
v = np.vstack([x2, y2])
print(v)

[[1 2 4 5]
 [3 4 6 7]]
[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [105]:
x2 = np.array([[1,2], [3,4], [5, 6]])  # 2x2

# hsplit  행 분할
h2 = np.hsplit(x2, 2)
print(h2)  
# -> array([[1],[3],[5]]) / array([[2],[4],[6]])


# vsplit  열 분할
v2 = np.vsplit(x2,3)
print(v2)
# -> [array([[1, 2]]), array([[3, 4]]), array([[5, 6]])]

[array([[1],
       [3],
       [5]]), array([[2],
       [4],
       [6]])]


In [130]:
x5 = np.array([[1],[2],[3],[4],[5]])
print(x5)
print(x5.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
(5, 1)


In [131]:
x6 = np.array([[1, 2, 3, 4, 5]])
print(x6)
print(x6.shape)

[[1 2 3 4 5]]
(1, 5)


## 1.5 다양한 배열 만들기

In [121]:
zero = np.zeros([3,4])
print(zero)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
one = np.ones([3,4])
print(one)

In [ ]:
eye = np.eye(3)
print(eye)

# Numpy 제공 함수

In [123]:
# 절댓값
arr1 = np.array([-1, -2, -3, 4])
abs_arr = np.abs(arr1)

print(abs_arr)

[1 2 3 4]


In [125]:
# 제곱근
arr2 = np.array([1, 4, 9, 16])
sqrt_arr = np.sqrt(arr2)

print(sqrt_arr)

[1. 2. 3. 4.]


## 집계함수

In [127]:
# 평균
a = np.array([1, 2, 3, 4, 5])
a_mean = np.mean(a)

print(a_mean)  # float형으로 출력

3.0


In [139]:
# 중간값
b = np.array([1, 3, 5, 7, 9])
b_median = np.median(b)

print(b_median)  # float형으로 출력

5.0


In [134]:
# 표준편차
c = np.array([1, 2, 3, 4, 5])
c_std = np.std(c)

print(c_std)

1.4142135623730951


In [135]:
# 분산
d = np.array([1, 2, 3, 4, 5])
d_var = np.var(d)

print(d_var)  # float형으로 출력

2.0


In [ ]:
# 합
d = np.array([1, 2, 3, 4, 5])
d_sum = np.sum(d)

print(d_sum)

In [136]:
# 누적합계 (배열 형태로 반환)
d_cumsum = np.cumsum(d)

print(d_cumsum)

[ 1  3  6 10 15]


In [140]:
# 최소값
min = np.argmin(d)

print(min) # 인덱스 값으로 출력. 0번째가 제일 작다

0


In [150]:
# 최대값
max = np.argmax(d)

print(max) # 인덱스 값으로 출력. 0번째가 제일 작다

4


In [141]:
# any -> 배열 안에 하나라도 True가 있는지 확인
a = np.array([0, 0, 0, 1])
a_true = np.any(a)

print(a_true)

True


In [142]:
# all -> 모두 True가 아니라면 False
a_all = np.all(a)
print(a_all)

False


In [145]:
# Nan/ nansum -> nan값이 있을 때 0으로 취급하여 더하기
a = np.array([1, 2, np.nan, 4])
a_nsum = np.nansum(a)
a_sum = np.sum(a)

print(a_sum)
print(a_nsum)

nan
7.0


In [149]:
# where -> 조건에 맞는 값을 출력
d = np.array([1, 2, 3, 4, 5])
condition1 = np.where(d < 3)
condition = np.where(d < 3, d, 0)

print(condition1) # 튜플형태로 출력 / 값이 없어도 출력?
print(condition)  # 배열형태로 출력

(array([0, 1]),)
[1 2 0 0 0]


### Boolean Indexing

조건에 따른 요소들을 판별해서 새로운 배열을 만든다.

In [155]:
# 조건에 맞는 값을 출력?
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_a = a[a % 2 == 0]

print(even_a)
print(a)

[ 2  4  6  8 10]
[ 1  2  3  4  5  6  7  8  9 10]


### Broadcast (브로드캐스트)

- 크기가 다른 배열 간의 연산도 가능하게 해줌
- ex) 1차원, 2차원

In [156]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

c = a + b
print(c)

[5 7 9]


In [166]:
d = np.array([[1],[2],[3]])  # 3 x 1
e = np.array([4, 5, 6])   # 원래라면 ([[4, 5, 6]])으로 해야함 1 x 3
f = d + e

print(d.shape)
print(e.shape)
print(f)

(3, 1)
(3,)
[[5 6 7]
 [6 7 8]
 [7 8 9]]


- 두 배열의 차원 수가 다를 경우, 더 작은 차원의 배열에 큰 차원의 배열이 맞을 때가지 1을 추가한다.

- 두 배열의 차원 수가 같을 경우에도, 크기가 1인 차원이 있다면 다른 배열의 크기와 일치하도록 복제한다.

- 두 배열의 차원 수가 같은 경우에도, 모든 차원의 크기가 같거나 크기가 1이라면 모양이 같은 두 배열의 요소 간 연산을 한다.

In [169]:
z = np.array([[1,2,3]])
print(z.shape)

(1, 3)


# 연습문제

In [220]:
import numpy as np

In [178]:
# 4.1 주어진 여러 개의 1차원 배열을 연결하여 하나의 큰 1차원 배열로 반환하세요.

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr3 = np.array([7, 8, 9, 10])

# concat 함수
a = np.concatenate([arr1,arr2,arr3])
print(a)
print(a.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)


In [260]:
# 4.2 주어진 2차원 배열에서 각 열의 평균값을 계산하여 새로운 1차원 배열로 나타내세요.
# mean() 함수 응용하기

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
c = []

for i in range(len(arr[0])):
  b = np.mean(arr[i])
  c.append(b)
  d = np.array(c)

print(d)
print(d.ndim)  # 차원 확인

[2. 5. 8.]
1


In [263]:
# 4.3 주어진 2차원 배열에서 각 행의 최대값을 구하여 1차원 배열로 반환하세요.
# np.max()

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

arr_max1 = arr.max(1)
print(arr_max1)

# np.max(arr, axis=1)

array([3, 6, 9])

In [226]:
# 4.4 0에서 1사이의 값으로 크기 10개의 1차원 배열을 만들어주세요.
# np.linspace(시작범위, 끝범위, num개수)

x = np.linspace(0,1,10)
print(x) 

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [264]:
# 4.5 주어진 1차원 배열에서 짝수인 요소들의 합을 계산하는 함수 sum_of_evens를 작성하세요.
# def sum_of_evens(arr: np.ndarray) -> int:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even = arr[arr % 2 == 0]
es = np.sum(even)
print(es)

# def sum_of_evens(arr: np.ndarray) -> int:
#     evens = arr[arr % 2 == 0]  # 짝수인 요소 선택
#     return np.sum(evens)  # 짝수인 요소들의 합 반환

30


In [ ]:
# 4.6 수평분할, 수직분할, 수평 스택, 수직 스택 문제를 풀어봅시다.

# 분할할 배열 생성
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

# 1. 수평분할하기 
harrd = np.hsplit(arr,2)
print(harrd)

# 다시 원본으로 스택쌓기
harrs = np.hstack(harrd)
print(harrs)

# arr_1 = arr_split[0]
# arr_2 = arr_split[1]
# arr_stack = np.hstack((arr_1, arr_2))
# print(arr_stack)

# 2. 수직분할하기 
varrd = np.vsplit(arr,3)
print(varrd)

# 다시 원본으로 스택쌓기
varrs = np.vstack(varrd)
print(varrs)

# arr_1 = arr_split[0]
# arr_2 = arr_split[1]
# arr_3 = arr_split[2]
# arr_stack = np.vstack((arr_1, arr_2, arr_3))
# print(arr_stack)

In [251]:
# 4.7 배열에서 조건에 맞는 값 반환하는 문제를 풀어봅시다.
# 조건 : 값을 10으로 나누었을 때 나머지가 0이면 원래 값 출력, 아니면 0으로 출력하세요.
arr = np.arange(0, 100, 5).reshape((5,4))

# a = arr[arr % 10 == 0]
# print(a)

a10 = np.where(arr % 10 == 0, arr, 0)
print(a10)

[[ 0  0 10  0]
 [20  0 30  0]
 [40  0 50  0]
 [60  0 70  0]
 [80  0 90  0]]


In [254]:
# 4.8 [3x3]배열 lst 중 짝수만 뽑아내는 부울린 인덱싱 배열(numpy 배열)을 사용하여 짝수 배열 n 을 만드시오
lst = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]
a = np.array(lst)

n = a[a % 2 == 0]
print(n)

[2 4 6 8]


In [267]:

bool_indexing_array = np.array([
    [False,  True, False],
    [True, False,  True],
    [False,  True, False]
])
# 1-----------------------------------
# n = a[bool_indexing_array];
# print(n)    

# 2-----------------------------------
# bool_indexing = (a % 2 == 0)
# print(bool_indexing)
# print(a[bool_indexing])

# 3-----------------------------------
# n = a[ a % 2 == 0 ]
# n

array([2, 4, 6, 8])

In [256]:
# 4.9 각도를 이용해서 삼각함수를 만들어봅시다.
angle = np.pi / 3 # 라디안 표기 = 60도 
# 360도는 2라디안 으로, 180도는 1라디안으로 표현합니다.

# 사인 함수 계산
sin_value = np.sin(angle)
print("사인 값:", sin_value)

# 코사인 함수 계산
cos_value = np.cos(angle)
print("코사인 값:", cos_value)

# 탄젠트 함수 계산
tan_value = np.tan(angle)
print("탄젠트 값:", tan_value)

62.831853071795855

In [258]:
# 4.10 조건함수를 사용해서  짝수조건을 만족하는 요소의 값이 2배로 만드는 배열을 만드시오.
arr = np.array([1, 2, 3, 4, 5])

arre2 = np.where(arr % 2 == 0, arr, 0)
anr = arre2 *2

print(anr)

# new_arr = np.where(arr % 2 == 0, arr * 2, arr)
# print("조건을 만족하는 요소를 2배로:", new_arr)

[0 4 0 8 0]
